### ISSUE TITLE
[1.10.2] Bypass Wireless Access Point through Infinity Booster Card

### ISSUE THREAD

**Issue by Hodel1** [p455w0rd/WirelessCraftingTerminal#142]
Hi,

i found a little "bug", after i moved my ME to another location, i forgot to place the Wireless Access Point and i wonder, why i can use my Wireless Crafting Terminal.

If you link you Wireless Crafting Terminal with your Security Terminal and place once a Wireless Access Point, you can insert a Wireless Booster Card. After this you can break your Wireless Access Point and you got further access to your Crafting Terminal.

I have made a short video for this :D
https://puu.sh/vCCO6/d5f1c686a7.mp4

I don't want to spam your repo, of course! (Answer to latest comment by another bug) :)

Tested on FTB Beyond 1.5.3 with Wireless Crafting Terminal 0.1.27 and AE2 rv4-alpha-11

**Comment by p455w0rd** [comment]
so this is actually how it's supposed to function at the moment, tho I will consider adding the check for the WAP as a new feature as it probably should..I purposely override the AE2 check since it also checks for the number of booster cards in the WAP and the distance (it's a good part of what lets the Infinity Booster Card function)

**Comment by p455w0rd** [comment]
i've decided to leave this as is for now..might change in the future
