### ISSUE TITLE
WCT handler attempts to handle other wireless terminals, preventing them from working.

### ISSUE THREAD

**Issue by Stalkstalks** [p455w0rd/WirelessCraftingTerminal#152]
I found that WCT was preventing modular power suits's wireless terminal module from working - the WCT handler reports that it can handle the terminal (because it does so for anything, though AE's own terminal handler is higher priority), and then returns that it is out of energy because the power fist doesn't store AE power directly, but converts from MPS's energy system.

There may be other wireless terminal items out there that are also having their own handlers supplanted by the WCT one - though since it may result in all of them getting the additional WCT functionality, maybe nobody cares.

Adding a check to the canHandle function in ItemWirelessCraftingTerminal so that it only attempts to handle WCTs themselves would fix this.

**Comment by p455w0rd** [comment]
You sound like you know what you're talking about so I'll mark this as a bug and implement the fix you suggest as ity sounds reasonable enough..or you can fork make a PR so that you get credited properly..let me know if you wanna do the PR :) Also thanks for the report!

**Comment by Stalkstalks** [comment]
Pull request at #153

**Comment by Stalkstalks** [comment]
Hey, I noticed this problem was back in the current release, and it looks like you rolled back the change from my pull request when you were adding IC2 support. Was that on purpose? Was it causing some other problem?

**Comment by p455w0rd** [comment]
no, not intentional...i had a weird situation happen where it would compile fine, but kept throwing a NoClassDefFoundError..even though I could open the jar and the class was clearly there...It is VERY odd, however, because I rectified  the situation by re-cloning the branch, re-adding IC2 suport and building...but since I re-cloned the branch, it should've pulled these changes too I would have thought...odd..anyway..I've readded the code in dev..I still have some stuff to do before pushing, but the code has been re-added in-dev..huge thanks for noticing and letting me know :)
