### ISSUE TITLE
[1.10.2] Crafting Terminal GUI not working

### ISSUE THREAD

**Issue by DrummerMC** [p455w0rd/WirelessCraftingTerminal#195]
![image](https://user-images.githubusercontent.com/7688760/32408849-27fa5588-c1a0-11e7-816a-f3868d7cd5c8.png)
Forge Version: 12.18.3.2511 (latest)

**Comment by p455w0rd** [comment]
yup found where it's at..it's due to me switching over to using AE's slots, rather than my copies of them...will take a bit of time to resolve unelss I just reimplement my copied slots..was trying to reduce the size of the codebase..I'll get something figure out when I have time....however it won't be long before I stop supporting 1.10 all together..it's obsolete

**Comment by drunkripper** [comment]
Is there any way I could help? Been a while since I did java, but I love WCT cause it makes it so much easier.

**Comment by p455w0rd** [comment]
I'll be uploading a fixed version in the next 15 mins :)

**Comment by p455w0rd** [comment]
Just waiting on CurseForge :)
