### ISSUE TITLE
Possible problem with integration of industrialcraft

### ISSUE THREAD

**Issue by BakermanLP** [p455w0rd/WirelessCraftingTerminal#24]
Hello,

I have a problem with wireless crafting terminal. Without the mod I get:
- Industrial Craft 2 - Integration Enable

With your mod (version WirelessCraftingTerminal-1.7.10-rv3-1.5.4b.jar) I get:
- Industrial Craft 2 - Integration Disabled

Is this possible and can you fix that?

**Comment by p455w0rd** [comment]
I need information. Are you using RV2 or RV3? I have IC2 installed on my dev env, though if what you mean is that AE2 disabled IC2 integration, I don't see how my mod could possibly effect this. I may have a solution however if this is the case.

**Comment by kuba12345** [comment]
p455w0rd is there any way to send private message to you ?

**Comment by p455w0rd** [comment]
Twitter/IRC..for Twitter, just follow me and I'll follow back and we can DM. Ore you can hop on IRC. If you don't have an IRC client, you can use mibbit (https://client02.chat.mibbit.com/) click the little "Server" link..in there server field, put irc.esper.net, choose a nickname, and for channel put #p455w0rdCraft

**Comment by p455w0rd** [comment]
Okay, well this is happening for me..I rly don't get it atm. Will definitely look further into it though, thanks for posting the issue

**Comment by BakermanLP** [comment]
OK, all mod versions we use can be found here (also the changed configs):
https://github.com/BakermanLP/ProjectRETv8/blob/master/Versions.md
https://github.com/BakermanLP/ProjectRETv8

**Comment by p455w0rd** [comment]
i was referring to my mod..which isn't in that list..rv2 or rv3?

**Comment by BakermanLP** [comment]
Was in the initial post of this issue:
- WirelessCraftingTerminal-1.7.10-rv3-1.5.4b.jar

**Comment by p455w0rd** [comment]
ok, i'll be looking into this..in the mean time I just posted v1.6b to CurseForge if you want to check it out

**Comment by p455w0rd** [comment]
well you seem to have pointed what turns out to be a very important bug..I don't know why, by my coremod isn't functioning correctly I've edited the hell out of it using direct references to a specific class and still nothing (it does load the NEI/RF stuff properly though..weirdness)..anyway, I'm working on removing the coremod completely and I hope this rectifies the issue..hang in there

**Comment by p455w0rd** [comment]
well..now that I have my coremod removed, it appears that ae2 ic2 integration is working again =] so I gotta completely rewrite my NEI integration (the shift-click [?]) thing since it was relying on my coremod before and then I want to figure out a way to not have to make users download NEI along with my mod (even though if you're downloading via Curse App this would be done automatically). I just don't want users to HAVE to have in case they aren't using NEI..so yeah...may be a bit before I get this all back and working, but IC2 should be back in next update

**Comment by p455w0rd** [comment]
http://prntscr.com/b17mvn =D
