### ISSUE TITLE
Shift+9 Crashes Server (When Wireless Crafting Terminal is in 9th hotbar slot)

### ISSUE THREAD

**Issue by Kr0goth** [p455w0rd/WirelessCraftingTerminal#275]
While using the Wireless Crafting Terminal (its interface is open), and not having clicked in the search/text field, if I hit shift+9 (for an opening parenthesis), the server crashes, and my Wireless Crafting Terminal has been deleted from my inventory once I get back into the game.

If I click in the search/text field, there is no issue. I can type "(legacy" without crashing the server.

Wireless Crafting Terminal version: 1.12.2-3.9.64
Modern Skyblock 3 version: 3.4.1.2

**Comment by ZombieKonsti** [comment]
I looked at that because it seems wiered ... It also works with Shift + 8 in the 8th slot. What happens is that the WCT gets shifted into the Crafting field and then the Sercer crashes. 
I also have a Crash log from that problem:

https://hastebin.com/zofudacefu.coffeescript

I hope i can help you with that.

**Comment by p455w0rd** [comment]
just replicated in RV5 and RV6 live on stream and fixed it :D thanks for the reports! just doing a RV6 test to ensure the fix works there as well, then I'll push fixes
