### ISSUE TITLE
Time Estimation in Crafting Status

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#46]
A small feature suggestion: The wct could show the eta from AE2 (rv3) in the title, such as the AE-native wireless terminal.

**Comment by p455w0rd** [comment]
i know..it was srsly a pain just to get the Co-Processors/craft size to display..But now that I have that sorted, maybe it won't be too difficult..I'll look into it

**Comment by condensedapple** [comment]
It is really not that important, I did notice _today_ that the time estimation is missing ;)

**Comment by p455w0rd** [comment]
i'm sorry but after looking into it, I feel it isn't going to happen. I will make sure it works in 1.9 version though ;)

**Comment by condensedapple** [comment]
I am sure the AE port to 1.9 wont take that long as you stated that you are helping ;)

**Comment by p455w0rd** [comment]
*will be* helping lol...from what I understand the main thing left is rendering..and I'm not sure how they want to go about doing that...but that's for the 1.8.9 version..I said that I would personally do the conversion from 1.8.9 to 1.9 (and/or 1.9.4) from 1.8.9 because that's easy compared to the tons of rendering work needed to get it going on 1.8...if I wasn't so deep in my own project, I'd do the rendering needed, but I want to get my 1.9 mod out in time for #BTM

**Comment by condensedapple** [comment]
thanks for the clarification. nice to see you at btm
